### ISSUE TITLE
Decision SDK Request w/ "count" of 7 or higher seems to silently fail.

### ISSUE THREAD

**Issue by JasonSlingsCode** [adzerk/adzerk-decision-sdk-js#17]
```js
const adzerk = require("@adzerk/decision-sdk")
let client = new adzerk.Client({ networkId: xxxxx });
let request = {
  placements: [
    {
      adTypes: [ 91 ],
      siteId: xxxxx,
      zoneIds: [ xxxxx ],
      count: 7,
      divName: 'div1,
      adQuery: {
        categoryId: { min: 20, max: 20, required: true },
        subcategoryId: { min: 191, max: 191, required: true }
      },
      properties: { categoryId: xxxxx, subcategoryId: xxxxx, deliveryZoneId: xxxxxx },
      eventIds: [ 3, 60, 62 ]
    }
  ],
  user: { key: 'not-yet-implmented' }
}
client.decisions.get(request).then(response => {
  console.dir(response, { depth: null });
})
.catch(err => console.err(err))
.finally(console.log('finished'));
```

^ The above SDK request seems to consistently fail when the count is set to 7. It consistently returns a response when it's 6 or under.

Current SDK version:

`"@adzerk/decision-sdk": {
      "version": "1.0.0-beta.5",
      "resolved": "https://registry.npmjs.org/@adzerk/decision-sdk/-/decision-sdk-1.0.0-beta.5.tgz",
      "integrity": "sha512-/iEEQXwomptrGn7Vdvv9I932LsmiYqiAoStib6MIglhcZ5ThJ4YVKC9CwGF+qykWRBQHzr3WSn24prdy9TCHZg==",
      "requires": {
        "debug": "^4.1.1",
        "form-data": "^2.5.1",
        "isomorphic-unfetch": "^3.0.0"
      }
    },`

**Comment by CrshOverride** [comment]
Our SDK uses `node-fetch` internally. I have manually verified that we're getting bit by the same root issue found in https://github.com/node-fetch/node-fetch/issues/739 which will be addressed by https://github.com/node-fetch/node-fetch/pull/1064.

I'm attempting to find a workaround until that PR gets merged/released.

**Comment by CrshOverride** [comment]
Workaround was implemented in https://github.com/adzerk/adzerk-decision-sdk-js/commit/a58853ee6f40c34871c856b1dd7dcc9a81f1f07b.

**Comment by CrshOverride** [comment]
Workaround implemented in https://github.com/adzerk/adzerk-decision-sdk-js/commit/a58853ee6f40c34871c856b1dd7dcc9a81f1f07b.
