### ISSUE TITLE
demo fetch request blocked by adblock plus plugin but the blog shows use this api can resolve blocked question

### ISSUE THREAD

**Issue by satomiyoyi** [adzerk/adzerk-decision-sdk-js#40]
the blog which i read:https://www.kevel.co/blog/how-ad-blockers-work
I am Chinese reader so the ads hit the easylistchina rule of adblock plugins:
https://easylist-downloads.adblockplus.org/easylistchina.txt

**Comment by karnowski** [comment]
Were you trying to fetch an ad from the web browser but saw it blocked?  Could you please post your sample request?  Or, if you're concerned about posting that publicly here on Github, would you please consider emailing it to support@kevel.co ?

**Comment by satomiyoyi** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>testdemo</title>
</head>

<body>
    <script src="https://unpkg.com/@adzerk/decision-sdk@1.0.0-beta.2/dist/adzerk-decision-sdk.js"></script>
    <script>
        let client = new AdzerkDecisionSdk.Client({ networkId: 23, siteId: 667480 });
        let request = {
            placements: [{ adTypes: [5] }],
            user: { key: "abc" },
            keywords: ["keyword1", "keyword2"]
        };
        client.decisions.get(request).then(response => {
            console.dir(response, { depth: null })
        });
    </script>
</body>

</html>`
Thanks for your reply
I make a test html page as shown above and use  domain '4.lovedword.com' to visit the page.
The fetch request blocked by the rule "||adzerk.net^$third-party".
The following picture show more detail.
Thanks for your kind attention and look forward your prompt reply
![image](https://user-images.githubusercontent.com/12145379/134608199-a9da5f14-9f23-41d1-87d3-01adcaa59dba.png)

**Comment by karnowski** [comment]
By default our SDK assumes your service is running on a subdomain of `adzerk.net`.  However, if you are a customer you can use the Custom Domain feature to white-label our service to your own domain and bypass that ad blocker rule.  The SDK supports this by accepting a "host" key when creating the `Client` object.   See the code here: 
https://github.com/adzerk/adzerk-decision-sdk-js/blob/cea0d4b3f490509bf75b2bc41264e7220c97dfc6/src/client.ts#L356

Given this work-around, I'm closing this issue.  Thanks for reaching out!
