### ISSUE TITLE
NextJs - Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by renegarcia225** [adzerk/adzerk-decision-sdk-js#91]
There's an error when trying to build a NextJS v13 project using ` @adzerk/decision-sdk 1.0.0-beta.25`, it just says `Critical dependency: the request of a dependency is an expression without any other description.
`
```
./node_modules/@adzerk/decision-sdk/lib/client.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@adzerk/decision-sdk/lib/client.js
./node_modules/@adzerk/decision-sdk/lib/index.js
```

**Comment by vkurup** [comment]
With a test project using next.js 13.5.6 and decision sdk beta.25, we were not able to replicate the issue.

A quick google search shows that there seem to be similar issues with people using Next.js.

Some suggestions are:
* Making sure all the dependencies are installed properly. Maybe remove node_modules folder and install the dependencies from scratch;
* Removing adzerk decision sdk, and see if the project runs with just Next.js; and
* Downgrade to beta.24 or beta.23 and see if the user gets the same error.
